title   = "Undus' Blog"
baseURL = "https://undus.net/"
theme   = "hugo-pure"
paginatation.pagerSize = 6
enableEmoji = true

[markup]
[markup.highlight]
noClasses = false
[markup.tableOfContents]
endLevel  = 3

[permalinks]
[permalinks.page]
posts = "/:sections[0]/:slugorcontentbasename/"
archives = "/:sections[0]/:slugorcontentbasename/"

[params]
#doubleColumns = true
description = "Keep it simple."

[menus]

[[menus.main]]
identifier = "root"
pageRef    = "/"
name       = "UNDUS' BLOG"
weight     = 1

[[menus.main]]
identifier = "mood"
pageRef    = "mood"
name       = "MOOD"
weight     = 3

[[menus.footer]]
name        = "🄯2023-2025"
weight      = 1
[menus.footer.params]
type = "plain"

[[menus.footer]]
identifier  = "rss"
name        = "Feed"
pageRef     = "/"
weight      = 3
[menus.footer.params]
targetBlank = true
format      = "rss"

[[menus.footer]]
identifier  = "github"
name        = "Github"
url         = "https://github.com/undus5"
weight      = 5
[menus.footer.params]
targetBlank = true

[[menus.footer]]
identifier  = "archives"
name        = "Archives"
pageRef     = "/archives"
weight      = 7

